name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  verify:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build documentation
      uses: docker://decathlon/slate-builder-action:latest
      env:
        DOC_BASE_FOLDER: ./source/includes
        ZIP_BUILD: true