name: Build and Deploy

on:
  push:
    branches: [ 'feature/setting_up_git_actions' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    env:
      external-doc-build: external_build
      internal-doc-build: internal_build

    steps:
    - name: Accessing github project files
      uses: actions/checkout@v2

    - name: Build internal and external document
      ## Use our deploy docker file
      ## Which sets up the ruby env to build the slate template
      uses: ./
      env:
        EXTERNAL_DOC_BUILD: ${{ env.external-doc-build }}
        INTERNAL_DOC_BUILD: ${{ env.internal-doc-build }}