name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  verify-template-resource:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        resource: [
          "index.html.external.md", 
          "index.html.internal.md",
          "fonts",
          "includes",
          "javascripts",
          "layouts",
          "stylesheets"
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Validate Resource
      run: |
        FILE=./source/${{ matrix.resource }}
        RESOURCE_TYPE=-d
        if [[ ${{ matrix.resource }} == *.* ]] ; then
        RESOURCE_TYPE=-f
        fi
        echo "$FILE $RESOURCE_TYPE"
        if test $RESOURCE_TYPE "$FILE"; then
          echo "Resource $FILE exists."
        else
         echo "Resource $FILE does not exist exists."
        fi
      