name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  verify:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: files-filter
      uses: wcchristian/gh-pattern-filter-action@master
      with:
        args: .*\\.md$
    - name: Build documentation
      uses: docker://decathlon/slate-builder-action:latest
      env:
        DOC_BASE_FOLDER: .
        ZIP_BUILD: true