name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  verify-template-files:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        resource: [
          "index.html.external.md", 
          "index.html.internal.md",
          "fonts",
          "includes",
          "javascripts",
          "layouts",
          "stylesheets"
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Validate files and folders
      run: |
        FILE=./source/${matrix.resource}
        echo "$FILE"
        if test -f "$FILE"; then
            echo "$FILE exists."
        fi
      # run: |
      #   chmod +x "${GITHUB_WORKSPACE}/.github/build.sh"

      #   # run script
      #   "${GITHUB_WORKSPACE}/.github/script.sh"
      env:
        IS_EXTERNAL: true
      